#!/usr/bin/expect

# Boot a image and login for you to setup the environment.

if {$argc != 1} {
    puts "Usage: ./qemurun.exp <ssh port>\r"
    exit 1
}

set timeout 120
set sshPort [lindex $argv 0] 

spawn build/qemu-release/i386-softmmu/qemu-system-i386 image/s2e_disk.raw -redir tcp:$sshPort\::22 -nographic

expect {
    "login:" { send "littlepunpun\n" }
}

expect {
    "Password:" { send "1234\n" }
}

interact
