#!/usr/bin/expect

set timeout 120

#spawn /home/chengte/SCraxF/build/qemu-release/i386-softmmu/qemu-system-i386 /home/chengte/disk_images/decree.raw -m 1024 \
#-nographic

spawn /home/chengte/SCraxF/build/qemu-release/i386-softmmu/qemu-system-i386 /home/chengte/disk_images/decree.raw -m 1024 

#while {1} {
#    expect {
#        "crs login:" { send "vagrant\n" }
#        timeout { set timeout 120 }
#    }
#    expect {
#        "Password:" {
#            send "vagrant\n"
#            break 
#        }
#        timeout { set timeout 120 }
#    }
#}

#interact
