#!/usr/bin/expect
#Run qemu in non-s2e mode and login in to setup the guest environment.
#Usage: ./runqemu.exp

set timeout 150

spawn /home/chengte/SCraxF/build/qemu-release/i386-softmmu/qemu-system-i386 /home/chengte/disk_images/s2e_guest.raw -m 1024 \
-nographic

interact \x0D {send "\x0D"; return}

while {1} {
    expect {
        "debian login:" { send "chengte\n" }
    }
    expect {
        "Password:" {
            send "s2e\n"
            break 
        }
    }
}

interact
