#!/usr/bin/expect
#Boot .s2e image in non-s2e mode and save snapshot automatically.
#Usage: ./savesnapshot.exp <snapshot-name>

set timeout 150

if {$argc != 1} {
    puts "Usage: ./savesnapshot.exp <snapshot-name> \r";
    exit 1
}

set snapshot_name [lindex $argv 0]

spawn /home/chengte/SCraxF/build/qemu-release/i386-softmmu/qemu-system-i386 /home/chengte/disk_images/s2e_guest.raw.s2e -net none \
-nographic
set guest_sid $spawn_id

interact \x0D {
    send "\x0D"
    return
}

expect "debian login:" { send "chengte\n" }
expect "Password:" { send "s2e\n" }
expect "@debian:" { send "\x01"; send "c" }
expect "(qemu)" {
    send "savevm $snapshot_name\n"
    send "quit\n"
}

wait -i $guest_sid
close -i $guest_sid
