#!/bin/sh

if [ $# -ne 1 ] ; then
    echo "Usage: ./s2erun SnapshotName"
    exit
fi
build/qemu-release/i386-s2e-softmmu/qemu-system-i386 image/s2e_disk.raw.s2e -s2e-config-file config.lua -s2e-verbose -net none -loadvm $1 #:vnc :1
